### ISSUE TITLE
Tv shows wont play

### ISSUE THREAD

**Issue by ttx99** [Ciarands/vidsrc-to-resolver#5] opened 2024-01-05 07:54 UTC
with fmovies as reference there should be a video available right and tmdb id does match

in fmovies it plays
![Screenshot_2024-01-05_15-46-48](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/ddd20ad5-53d3-40ec-b9a5-c16166cad676)
![Screenshot_2024-01-05_15-46-24](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/42b76ae9-5531-4cd6-bfe6-5b9fe3c784d8)

TMDB and CLI ID match
![Screenshot_2024-01-05_15-48-12](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/bb40fa5a-3a0f-4667-8749-16d422d4a3dd)
![Screenshot_2024-01-05_15-48-47](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/68ca4fde-a37a-4b27-983c-87862a748bc8)
![Screenshot_2024-01-05_15-50-41](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/c45bca00-c973-4d4b-86f1-273f7050af72)

**Comment by ttx99** [comment] 2024-01-05 07:58
But I do understand that not all search results does have a video content uploaded to vidsrc. So i use fmovies as reference

**Comment by ttx99** [comment] 2024-01-05 08:07
Weird filemoon plays the video
![Screenshot_2024-01-05_16-06-15](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/f8b3484e-4504-47b1-80b9-600bccab9f3e)

**Comment by ttx99** [comment] 2024-01-05 08:11
filemoon lost tapes s01ep02 wont play
![Screenshot_2024-01-05_16-10-58](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/6ab43762-24d3-4ad2-bec6-fa94c6198e39)

**Comment by Ciarands** [comment] 2024-01-05 09:27
> filemoon lost tapes s01ep02 wont play ![Screenshot_2024-01-05_16-10-58](https://private-user-images.githubusercontent.com/95531944/294431322-6ab43762-24d3-4ad2-bec6-fa94c6198e39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDY0NjIsIm5iZiI6MTcwNDQ0NjE2MiwicGF0aCI6Ii85NTUzMTk0NC8yOTQ0MzEzMjItNmFiNDM3NjItMjRkMy00YWQyLWJlYzYtZmE5NGM2MTk4ZTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA5MTYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNjVmMGYzZGQ0MTczNzdlNmMzNDQyOTRiMTA5ZTRlNWJmNGU5ODQ4NTJhZjNhYjFlNGIwNzU2ZmZhYTIyMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hXITUzqH4u-YZb33bdYvAX6_icheVpP5_aaphOb5lLU)

looks like a yt-dlp bug, could not reproduce, could you run `-logffmpeg` with the command and send the output?

**Comment by ttx99** [comment] 2024-01-05 10:20
works now thx bro
![Screenshot_2024-01-05_18-19-31](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/ebf1ea36-27b2-4872-b0e3-782e461a803a)

**Comment by ttx99** [comment] 2024-01-05 10:30
uhm btw if you still need the log file where do i find it? sorry noob linux user

**Comment by Ciarands** [comment] 2024-01-05 12:10
All good and there is no log file, was asking if you could pass "-logffmpeg" as an arg with the command then show the new output with no errors supressed.

**Comment by ttx99** [comment] 2024-01-06 03:47
![1](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/a179c0f3-68dc-4187-a46c-039eb7deb055)
![1](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/293688d9-11a2-4922-b2cc-fcf782b9551b)
![1](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/9b86e2c8-4805-4335-95c5-8137bd5db8b3)

**Comment by Ciarands** [comment] 2024-01-06 06:27
Sorry, should have specified, with Filemoon.

> filemoon lost tapes s01ep02 wont play ![Screenshot_2024-01-05_16-10-58](https://private-user-images.githubusercontent.com/95531944/294431322-6ab43762-24d3-4ad2-bec6-fa94c6198e39.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MjI1NjMsIm5iZiI6MTcwNDUyMjI2MywicGF0aCI6Ii85NTUzMTk0NC8yOTQ0MzEzMjItNmFiNDM3NjItMjRkMy00YWQyLWJlYzYtZmE5NGM2MTk4ZTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA2MjQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YzFjNGY2YjIzMWYzMzNhZGNhOGZiMjNhNzZiZTdjNGQwYWU1Y2U1ZGM3OThiNzMzMTkyY2ZhMWYzNjIwYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s-ZV75qw6A6p0y6uifcxP7jGvtUpnmRuwsStxAHQvnM)

I wanted you to try and reproduce this.

**Comment by ttx99** [comment] 2024-01-06 08:54
Can't anymore
![1](https://github.com/Ciarands/vidsrc-to-resolver/assets/95531944/57a3d984-48a6-4c48-9768-03d1672f49b4)

**Comment by ttx99** [comment] 2024-01-06 08:56
just saying you should probably name this script something different like the "lobster guy" , just saying bro.

**Comment by Ciarands** [comment] 2024-01-06 09:46
> Can't anymore ![1](https://private-user-images.githubusercontent.com/95531944/294661142-57a3d984-48a6-4c48-9768-03d1672f49b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1MzQ2NDUsIm5iZiI6MTcwNDUzNDM0NSwicGF0aCI6Ii85NTUzMTk0NC8yOTQ2NjExNDItNTdhM2Q5ODQtNDhhNi00YzQ4LTk3NjgtMDNkMTY3MmY0OWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDA5NDU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmOTM3YjEyOTc4ZjI4Yzk2ODUxOGY2YmQzMTc0Yjk4Yzk0YzQxYTEwYjU2MWFlYWFhY2NhNmY1YWZmODViNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O3OM58zD47RdOEPUQU7NBK2K8MrzdXQFE4VtenTackU)

weird yeah, seems to be an mpv/yt-dlp bug

**Comment by Ciarands** [comment] 2024-01-06 09:54
> just saying you should probably name this script something different like the "lobster guy" did , just saying bro.

I know the lobster guy, justchokingaround is cool. 
I have ideas for something of this nature, but rn this CLI is going to be specifically for this source, I may create a CLI that pulls from vidsrc.me, vidsrc.to, rabbitstream, megacloud, rapid-stream and showbox/superstream in future, but thats not currently in the works atm, I just have all the building blocks available.
Anyway im going to close this issue since its resolved now.

**Closed by Ciarands** 2024-01-06 09:54 UTC
